spring:
  application:
    name: spring-ai-rag-example
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      base-url: ${OPEN_AI_BASE_URL:https://api.openai.com}
      embedding:
        options:
          model: text-embedding-3-small
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  vectorstore:
    pgvector:
      index-type: HNSW
      distance-function: COSINE_DISTANCE
      dimensions: 1536
      max-document-batch-size: 10000

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
